### ISSUE TITLE
Oddities in MFX Metadata Namespace

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/Bug-Reports#2]
## Expected Behavior

`mfx.dg2.valve`

## Current Behavior

`mfx.dg2_valve`

## Context

Somehow, the valve names here aren't being split to the proper level

## Your Environment

`pcds-0.6.0`
dev only has transfocate

**Comment by ZLLentz** [comment]
Confirmed still happens with bleeding-edge `hutch-python` and `pcdsdevices`

**Comment by teddyrendahl** [comment]
@ZLLentz Was this resolved by https://github.com/pcdshub/hutch-python/pull/119

**Comment by ZLLentz** [comment]
@teddyrendahl yes, closing
