### ISSUE TITLE
Strange Behavior when Launching Hutch Python

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/Bug-Reports#7]
Looks like the new`hutch-python` was launched from inside the old `hutch-python` directory. Understandably the code got confused, but we should raise an Error and not crash

https://pswww.slac.stanford.edu/apps/portal/index.php?exper_id=794&app=elog:search&params=message:386990

**Comment by ZLLentz** [comment]
This would probably be fixed for good (including similar cases) if we implemented https://github.com/pcdshub/hutch-python/issues/127.

This probably is already fixed for the current dev patch thanks to a side-effect of https://github.com/pcdshub/hutch-python/pull/126

**Comment by teddyrendahl** [comment]
I'll try this in `-dev` just to make sure

**Comment by ZLLentz** [comment]
Closing old issue
